# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Code-Switched Text Generation Evaluation Challenge
short_description: Automatic evaluation metrics for code-switched text generation
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Accuracy scores for predicting human preferences in code-switched text generation
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2025-01-17 00:00:00
end_date: 2025-02-15 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Accuracy", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Accuracy": {
            "sort_ascending": False,
            "description": "Accuracy in predicting human preferences for code-switched text",
          },
          "Total": {
            "sort_ascending": False,
            "description": "Overall score (same as accuracy)",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Development Phase
    description: Development phase for the challenge
    start_date: 2025-01-17 00:00:00
    end_date: 2025-02-14 23:59:59
    max_submissions_per_day: 5
    max_submissions: 50
    is_public: true
    is_submission_public: true
    submission_meta_attributes:
      - name: method_name
        is_required: true
    allowed_submission_file_types: [".csv"]
    test_annotation_file: annotations/dev_phase_ground_truth.csv

  - id: 2
    name: Testing Phase
    description: Final testing phase for the challenge
    start_date: 2025-02-15 00:00:00
    end_date: 2025-02-15 23:59:59
    max_submissions_per_day: 1
    max_submissions: 1
    is_public: true
    is_submission_public: false
    submission_meta_attributes:
      - name: method_name
        is_required: true
    allowed_submission_file_types: [".csv"]
    test_annotation_file: annotations/test_phase_ground_truth.csv

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
